### ISSUE TITLE
Pass playlist image to ${playlistYaml}

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/seasonal-post-action#123]
Hi @katydecorah, would it be possible to pass the playlist image name to ${playlistYaml} so I can easily refer to it in my template? I'm having trouble with 11ty/slugify to convert {{ playlist }} (2022/2023 Summer) to 2022-2023-summer to display the image file.

**Comment by katydecorah** [comment]
@flamedfury would you mind sharing some more examples? I want to make sure I'm understanding your use case 😀

**Comment by flamedfury** [comment]
@katydecorah so from what I understand, when seasonal.yaml runs, it creates the season post, e.g. 2023-03-20-2023-summer.md

in the frontmatter of the post it give the following yaml per ${playlistYaml}

```yaml
playlist: 2022/2023 Summer
spotify: https://open.spotify.com/playlist/0udgwvWIVAG22pFvXn9I0e
tracks:
  - track: Flowers
    artist: Miley Cyrus
    album: Flowers
  - track: Bette Davis Eyes
    artist: Kim Carnes
    album: Mistaken Identity
  - track: Before You Leave
    artist: SIX60
    album: Castle St
  - track: Always Beside You (feat. SIX60)
    artist: COTERIE, SIX60
    album: COTERIE
```

what I was hoping to get was the generated cover image that the playlist action creates e.g.

```yaml
playlist: 2022/2023 Summer
cover: 2022-2023-summer.png
spotify: https://open.spotify.com/playlist/0udgwvWIVAG22pFvXn9I0e
tracks:
  - track: Flowers
    artist: Miley Cyrus
    album: Flowers
  - track: Bette Davis Eyes
    artist: Kim Carnes
    album: Mistaken Identity
  - track: Before You Leave
    artist: SIX60
    album: Castle St
  - track: Always Beside You (feat. SIX60)
    artist: COTERIE, SIX60
    album: COTERIE
```

Does that make sense?
